---
apiVersion: v1
kind: PersistentVolume
metadata:
  # The name of the PV
  name: pv-lustre-subdir
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    # This field should be the true size of the Azure Lustre you want
    # to used. So that, k8s can allocate resources better.
    storage: 4Ti
  csi:
    driver: azurelustre.csi.azure.com
    volumeAttributes:
      # The file system name of the existing Lustre
      fs-name: ${EXISTING_LUSTRE_FS_NAME}
      # The IP address of the existing Lustre
      mgs-ip-address: ${EXISTING_LUSTRE_IP_ADDRESS}
      # The subdirectory to create and mount per pod (cannot use pvc / pv metadata in static volumes)
      sub-dir: "${pod.metadata.namespace}_${pod.metadata.name}"
      # Whether the created subdirectory should be retained or deleted at pod exit
      # This parameter is required if "sub-dir" is provided
      retain-sub-dir: "false"
    # Make sure this VolumeID is unique in the cluster
    # volumeHandle format: {volume-name}#{fs-name}#{mgs-ip-address}#{sub-dir}#{retain-sub-dir}
    # Example: vol_1#lustrefs#0.0.0.0#example_sub_dir#true
    # If the value does not match this format, the driver will not attempt to create
    #   the configured subdirectory. Further, if retain-sub-dir is 'false' in that
    #   case, any attempt to mount this volume will fail.
    volumeHandle: ${UNIQUE_IDENTIFIER_VOLUME_ID}
  # "Delete" is not supported in static provisioning PV
  mountOptions:
    - noatime
    - flock
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
