---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # The name of the PVC
  name: pvc-lustre-subdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # The real storage capacity in the claim
      storage: 1Gi
  # This field must be the same as the storage class name in StorageClass
  storageClassName: subdir.azurelustre.csi.azure.com
