---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc.azurelustre.csi.azure.com
provisioner: azurelustre.csi.azure.com
parameters:
  mgs-ip-address: "10.0.0.10"      # dev1
  fs-name: "lustrefs"
mountOptions:
  - noatime
  - flock
